apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mqtt
  namespace: automation
data:
  mosquitto.conf: |
    persistence true
    allow_anonymous true
    listener 1883
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
