apiVersion: v1
kind: Service
metadata:
  name: svc-mqtt
  namespace: automation
  annotations:
    metallb.universe.tf/allow-shared-ip: "automation-shared-ip"
spec:
  selector:
    app: mqtt
  type: LoadBalancer
  loadBalancerIP: 192.168.68.222
  ports:
    - port: 1883
      targetPort: 1883