apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: network
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: vaisanenj/pihole:2022.03
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: pihole-cm
                key: TZ
          - name: DNS1
            valueFrom:
              configMapKeyRef:
                name: pihole-cm
                key: DNS1
          - name: DNS2
            valueFrom:
              configMapKeyRef:
                name: pihole-cm
                key: DNS2
          - name: WEBPASSWORD
            valueFrom:
              configMapKeyRef:
                name: pihole-cm
                key: WEBPASSWORD