apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: network
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: vaisanenj/pihole:2022.03
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: TZ
          - name: PIHOLE_DNS_
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: DNS
          - name: WEBPASSWORD
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: WEBPASSWORD