apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: automation
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-automation
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2022.3
          volumeMounts:
            - mountPath: /config
              subPath: homeassistant
              name: storage