apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homeassistant
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/nfsshare/K8s/homeassistant
    server: 192.168.68.201