apiVersion: v1
kind: Service
metadata:
  name: svc-homeassistant
  namespace: automation
spec:
  selector:
    app: homeassistant
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP