apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-security
  namespace: security
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: pv-nfs-security
