apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-media
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jellyfin.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-jellyfin
            port:
              number: 8096