apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media
  namespace: media
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: pv-nfs-media
