apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.4.6
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: storage 
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-grafana