apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plexserver-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/nfsshare/Media
    server: 192.168.68.201

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plexserver-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/nfsshare/K8s/plex
    server: 192.168.68.201