apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-zigbee2mqtt
  namespace: automation
  labels:
    app: zigbee2mqtt
data:
  configuration.yaml: |-

    # Let new devices join our zigbee network
    permit_join: true
    
    # Home Assistant integration (MQTT discovery)
    homeassistant: true

    # MQTT server URL
    mqtt:
      base_topic: zigbee2mqtt
      server: "mqtt://svc-mqtt.automation:31883"

    serial:
      port: /dev/ttyACM0
      adapter: deconz

    frontend:
      port: 8080

    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      log_level: debug
      log_output:
      - console
      - file

    ## Map devices to persistent /data directory
    devices: /data/devices.yaml
    groups: /data/groups.yaml