apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: automation
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.24.0
          securityContext:
            privileged: true
          volumeMounts:
            - name: ttyacm
              mountPath: /dev/ttyACM0
            - name: zigbee2mqtt-udev
              mountPath: /run/udev
            - name: data
              mountPath: /app/data
      volumes:
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        - name: zigbee2mqtt-config
          configMap:
            name: cm-zigbee2mqtt
        - name: zigbee2mqtt-udev
          hostPath:
            path: /run/udev
        - name: data
          persistentVolumeClaim:
            claimName: pvc-zigbee2mqtt