apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zigbee2mqtt
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/nfsshare/K8s/zigbee2mqtt
    server: 192.168.68.201