apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zigbee2mqtt
  namespace: automation
spec:
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: pv-zigbee2mqtt
      