apiVersion: v1
kind: Service
metadata:
  name: svc-zigbee2mqtt
  namespace: automation
spec:
  selector:
    app: zigbee2mqtt
  type: ClusterIP
  ports:
    - name: zigbee2mqtt
      port: 8080
      targetPort: 8080
      protocol: TCP