apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-openvpn
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/nfsshare/openvpn
    server: 192.168.68.240