apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openvpn
  namespace: security
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  volumeName: pv-openvpn
