apiVersion: v1
kind: Service
metadata:
  name: svc-openvpn
  namespace: security
spec:
  selector:
    app: openvpn
  type: NodePort
  ports:
    - name: port1194udp
      port: 1194
      nodePort: 31194
      targetPort: 1194
      protocol: UDP