apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitor
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.4.6
          env:
          - name: GF_SERVER_DOMAIN
            value: grafana.lan
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: data
              subPath: grafana 
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-monitor