apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.3.3
  name: grafana
  namespace: monitoring
  annotations:
    metallb.universe.tf/allow-shared-ip: "monitoring-shared-ip"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.68.226
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
