apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-monitor
  namespace: monitor
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: pv-nfs-monitor
