apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
spec:
  selector:
    matchLabels:
      app: openvpn
  replicas: 1
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc-openvpn
      containers:
        - name: openvpn
          image: mjenz/rpi-openvpn
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - mountPath: "/etc/openvpn"
              name: storage 