apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-openvpn
  namespace: network
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /dir/to/openvpn/
    server: <NFS-IP>