apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: security
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:2022.02
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: TZ
          - name: PIHOLE_DNS_
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: DNS
          - name: WEBPASSWORD
            valueFrom:
              configMapKeyRef:
                name: cm-pihole
                key: WEBPASSWORD
          command: ["bin/bash", "-c"]
          args: 
          - sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://blocklistproject.github.io/Lists/ads.txt', 1, 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://gist.githubusercontent.com/anudeepND/adac7982307fec6ee23605e281a57f1a/raw/5b8582b906a9497624c3f3187a49ebc23a9cf2fb/Test.txt', 1, 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://github.com/Ewpratten/youtube_ad_blocklist/blob/master/blocklist.txt', 1, 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^(.+[_.-])?telemetry[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^adim(age|g)s?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^adtrack(er|ing)?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^advert(s|is(ing|ements?))?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^aff(iliat(es?|ion))?[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^analytics?[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^banners?[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^beacons?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^count(ers?)?[0-9]*[_.-]', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^mads\.', '1', 'Included by YAML');";
            sqlite3 /etc/pihole/gravity.db "INSERT INTO domainlist (type, domain, enabled, comment) VALUES (3, '^pixels?[-.]', '1', 'Included by YAML');";
            /s6-init;