apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: security
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
   #   hostNetwork: true
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pvc-security
      containers:
        - name: pihole
          image: pihole/pihole:2022.02
          env:
          - name: TZ
            value: Europe/Helsinki
          - name: PIHOLE_DNS_
            value: 10.43.7.211#5335
          - name: WEBPASSWORD
            value: passu123
          volumeMounts:
            - mountPath: /etc/pihole
              subPath: pihole/config
              name: pihole-data
            - mountPath: /etc/dnsmasq.d
              subPath: pihole/etc-dnsmasq.d
              name: pihole-data