apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-automation
  namespace: automation
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: pv-nfs-automation
